#!/usr/bin/env bash
# ==============================================================================
# Wiz Module: Neovim Editor
# ==============================================================================
# Installs Neovim, a modern Vim fork with Lua configuration.
#
# Provides:
#   - Neovim editor
#   - Basic configuration
#
# Dependencies: essentials (for build tools if building from source)
#
# Usage:
#   ./install_neovim.sh
#   or sourced by bootstrap orchestrator
#
# ==============================================================================

set -euo pipefail

# --- Module Configuration ---
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Source module base
# shellcheck source=../module-base.sh
source "${SCRIPT_DIR}/../module-base.sh"

# Module metadata
MODULE_NAME="neovim"
MODULE_VERSION="0.2.0"
MODULE_DESCRIPTION="Neovim editor with Lua configuration"
MODULE_DEPS="essentials"

# Configuration
NEOVIM_CONFIG_DIR="$HOME/.config/nvim"

# --- Module Interface Implementation ---

# describe_neovim: Describe what this module will install
describe_neovim() {
    cat << EOF

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
📝 NEOVIM EDITOR
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This module installs Neovim, a modern Vim fork:

  🚀 Modern Vim:         Fork of Vim with better defaults
  ⚙️  Lua Config:         Configuration in Lua instead of VimL
  🔌 Plugin Support:      Compatible with Vim plugins
  🎨 Better UI:          Modern terminal UI features

Features:
  - Built-in LSP support
  - Async plugin support
  - Better performance
  - Terminal integration

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EOF
}

# install_neovim: Main installation logic
install_neovim() {
    # Check if neovim is already installed
    if check_command_installed nvim; then
        module_skip "Already installed (use --force to reinstall)"
        return 0
    fi
    
    log "Installing Neovim..."
    
    # Try apt installation first (fastest)
    # Note: apt-get update is handled by essentials module, so we skip it here
    if command_exists apt; then
        progress "Installing via apt..."
        run "sudo apt-get install -y neovim" && {
            success "Neovim installed via apt"
            configure_neovim
            return 0
        }
        warn "apt installation failed, trying alternative methods..."
    fi
    
    # Try snap installation
    if command_exists snap; then
        progress "Installing via snap..."
        run "sudo snap install nvim --classic" && {
            success "Neovim installed via snap"
            configure_neovim
            return 0
        }
        warn "snap installation failed"
    fi
    
    # Try AppImage installation as fallback
    log "Installing Neovim AppImage..."
    local appimage_dir="$HOME/.local/bin"
    mkdir -p "$appimage_dir"
    
    local appimage_url="https://github.com/neovim/neovim/releases/latest/download/nvim.appimage"
    local appimage_path="$appimage_dir/nvim"
    
    curl_or_wget_download "$appimage_url" "$appimage_path" "Failed to download Neovim AppImage" || {
        module_fail "Neovim AppImage download failed"
    }
    
    run "chmod +x '$appimage_path'"
    add_to_path "$appimage_dir"
    
    success "Neovim AppImage installed"
    configure_neovim
    
    return 0
}

# configure_neovim: Create basic Neovim configuration
configure_neovim() {
    log "Configuring Neovim..."
    
    # Create config directory
    mkdir -p "$NEOVIM_CONFIG_DIR"
    
    # Create basic init.lua if it doesn't exist
    local init_file="$NEOVIM_CONFIG_DIR/init.lua"
    
    if [[ ! -f "$init_file" ]]; then
        log "Creating basic Neovim configuration..."
        
        cat > "$init_file" << 'EOF'
-- Neovim configuration
-- Generated by Wiz - Terminal Magic

vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.tabstop = 2
vim.opt.shiftwidth = 2
vim.opt.expandtab = true
vim.opt.smartindent = true
vim.opt.wrap = false
vim.opt.swapfile = false
vim.opt.backup = false
vim.opt.undofile = true
vim.opt.hlsearch = true
vim.opt.incsearch = true
vim.opt.termguicolors = true
vim.opt.scrolloff = 8
vim.opt.signcolumn = "yes"

-- Set leader key
vim.g.mapleader = " "
vim.g.maplocalleader = " "

-- Key mappings
vim.keymap.set("n", "<leader>w", "<cmd>w<CR>", { desc = "Save file" })
vim.keymap.set("n", "<leader>q", "<cmd>q<CR>", { desc = "Quit" })
EOF
        
        success "Basic configuration created: $init_file"
    else
        debug "Configuration file already exists: $init_file"
    fi
}

# verify_neovim: Verify installation succeeded
verify_neovim() {
    log "Verifying Neovim installation..."
    
    local failed=0
    
    # Ensure nvim is in PATH if installed via AppImage
    add_to_path "$HOME/.local/bin"
    
    # Check nvim command exists
    if ! verify_command_exists nvim; then
        ((failed++))
    elif nvim --version >/dev/null 2>&1; then
        success "✓ nvim command working"
    else
        warn "nvim --version failed"
    fi
    
    # Check config directory
    verify_file_or_dir "$NEOVIM_CONFIG_DIR" "Neovim config directory" 1
    
    if [[ $failed -gt 0 ]]; then
        error "Verification failed with ${failed} error(s)"
        return 1
    fi
    
    success "Neovim installation verified successfully"
    return 0
}

# --- Main Execution ---

# If script is executed directly (not sourced), run the module
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    execute_module "neovim"
fi

